### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [dwdyer/familytree#1]
Hei,
This repository is missing a LICENSE.txt (or LICENSE.md). Under what license are you sharing or gifting this code? If you haven't yet considered choosing a license, you might find the [Choose a License website](https://choosealicense.com/) helpful.

Kiitos,
Brylie

**Comment by brylie** [comment]
I'm still researching open source genealogy tools, and found your tool again. Please consider adding a license, so I might be able to build on your work. :-)

**Comment by dwdyer** [comment]
Thanks for the reminder. I've just added the AGPL licence. You're welcome to fork this project and do what you want with it. Just be aware that it's far from complete. There are chunks of necessary functionality missing and a few choices that might need to be revisited. I've never had a particular goal in mind for it, I've just been playing around.
